version: '3.3'
services:
  db:
    image: mongo
    container_name: mongo-container
    volumes:
      - /db/data:/data/db
    restart: always
    ports:
      - "27017:27017"

  spring1:
    depends_on:
      - db
    build: .
    restart: always

  spring2:
    depends_on:
      - db
    build: .
    restart: always

  loadbalance:
    depends_on:
      - spring1
      - spring2
    image: nginx
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    command: [ nginx-debug, '-g', 'daemon off;' ]